import 'course.dart';
import 'coursecategory.dart';
import 'lecture.dart';
import 'section.dart';

class CourseDataProvider {

  //Section List
  static List<Section> sectionList = [
    Section("Introduction", [
      Lecture("Module Introduction", "02:25 mins"),
      Lecture("Creating New Project", "05:17 mins"),
      Lecture("Basics", "17:20 mins"),
      Lecture("Fundamentals", "11:10 mins"),
      Lecture("TEST", "07:40 mins"),
    ]),
    Section("Fundamentals", [
      Lecture("Module Introduction", "02:25 mins"),
      Lecture("Creating New Project", "05:17 mins"),
      Lecture("Basics", "17:20 mins"),
      Lecture("Fundamentals", "11:10 mins"),
      Lecture("TEST", "07:40 mins"),
    ]),
    Section("Theoretical Framework", [
      Lecture("Module Introduction", "02:25 mins"),
      Lecture("Creating New Project", "05:17 mins"),
      Lecture("Basics", "17:20 mins"),
      Lecture("Fundamentals", "11:10 mins"),
      Lecture("TEST", "07:40 mins"),
    ]),
    Section("Practical Applications", [
      Lecture("Module Introduction", "02:25 mins"),
      Lecture("Creating New Project", "05:17 mins"),
      Lecture("Basics", "17:20 mins"),
      Lecture("Fundamentals", "11:10 mins"),
      Lecture("TEST", "07:40 mins"),
    ]),
    Section("Tools and Techniques", [
      Lecture("Module Introduction", "02:25 mins"),
      Lecture("Creating New Project", "05:17 mins"),
      Lecture("Basics", "17:20 mins"),
      Lecture("Fundamentals", "11:10 mins"),
      Lecture("TEST", "07:40 mins"),
    ]),
    Section("Advanced Topics", [
      Lecture("Module Introduction", "02:25 mins"),
      Lecture("Creating New Project", "05:17 mins"),
      Lecture("Basics", "17:20 mins"),
      Lecture("Fundamentals", "11:10 mins"),
      Lecture("TEST", "07:40 mins"),
    ]),

    Section("Project Work", [
      Lecture("Module Introduction", "02:25 mins"),
      Lecture("Creating New Project", "05:17 mins"),
      Lecture("Basics", "17:20 mins"),
      Lecture("Fundamentals", "11:10 mins"),
      Lecture("TEST", "07:40 mins"),
    ]),

  ];

  //Course List
  static List<Course> courseList = [
    Course(
        "1",
        "HTML for beginners",
        "assets/images/c1.jpg",
        "Learn HTML from scratch with our hands-on course, covering everything from basic tags to advanced web structures. Build your foundation for creating visually appealing and well-structured web pages.",
        "Instructor:Colt Steele",
        "01-Jan-2022",
        4.2,
        false,
        CourseCategory.programming,
        100,
        '2.5 Hours',
        15,
        sectionList),
    Course(
        "2",
        "Intro to HTML",
        "assets/images/c2.jpg",
        "Master HTML with our comprehensive course, guiding you through fundamental elements and best practices. Gain the skills to create and structure engaging web content with ease.",
        "Instructor:Angela Yu",
        "01-Apr-2022",
        4.5,
        false,
        CourseCategory.programming,
        50,
        '3 Hours',
        10,
        sectionList),

    Course(
        "3",
        "Beginners CSS",
        "assets/images/c3.jpg",
       " Dive into CSS with our complete course, where you'll learn to style and design stunning web pages. From basic selectors to advanced layouts, master the art of creating visually appealing websites.,",
        "Instructor:Rob Perci",
        "01-Jan-2022",
        4,
        false,
        CourseCategory.programming,
        40,
        '5 Hours',
        30,
        sectionList),
    Course(
        "4",
        "CSS Crash Course",
        "assets/images/c4.jpg",
        "Unlock the power of CSS with our in-depth course, covering everything from foundational styles to complex responsive designs.",
        "Instructor:Y V Rao",
        "01-MAR-2022",
        4.2,
        false,
        CourseCategory.programming,
        75,
        '4 Hours',
        24,
        sectionList),

    Course(
        "5",
        "Python Basics",
        "assets/images/c5.jpg",
        "Explore the world of Python with our detailed course, covering everything from basic syntax to advanced programming concepts. ",
        "Instructor:Angela Yu",
        "01-MAR-2022",
        4.7,
        false,
        CourseCategory.programming,
        45,
        '4 Hours',
        60,
        sectionList),

    Course(
        "6",
        "How To Market",
        "assets/images/c6.jpg",
        "This is complete marketing master class. In this course, you will learn how to increase sales, approach new clients.",
        "Instructor:Jose Portilla",
        "01-MAR-2022",
        4.1,
        false,
        CourseCategory.marketing,
        75,
        '4 Hours',
        25,
        sectionList),

    Course(
        "7",
        "Financing",
        "assets/images/c7.jpg",
        "Master the fundamentals of finance with our course, covering essential topics like budgeting, investing, and financial analysis. Gain the knowledge to make informed financial decisions and achieve your financial goals.",
        "Instructor:Mark Price",
        "01-MAR-2022",
        4.3,
        false,
        CourseCategory.finance,
        150,
        '4 Hours',
        20,
        sectionList),

    Course(
        "8",
        "Finance Basics",
        "assets/images/c8.jpg",
        "Master the fundamentals of finance with our course, covering essential topics like budgeting, investing, and financial analysis. Gain the knowledge to make informed financial decisions and achieve your financial goals.",
        "Instructor:Ben Awad",
        "01-MAR-2022",
        4.8,
        false,
        CourseCategory.finance,
        50,
        '4 Hours',
        20,
        sectionList),

    Course(
        "9",
        "Marketing for Newbies",
        "assets/images/c9.png",
        "This is complete marketing master class. In this course, you will learn how to increase sales, approach new clients.",
        "Instructor:Anita Prakash",
        "01-MAR-2022",
        4.5,
        false,
        CourseCategory.marketing,
        70,
        '4 Hours',
        20,
        sectionList),

    Course(
        "10",
        "UIUX basics",
        "assets/images/c10.jpg",
        "This is complete marketing master class. In this course, you will learn how to increase sales, approach new clients.",
        "Instructor:Joseph Jostar",
        "01-MAR-2022",
        4.5,
        false,
        CourseCategory.other,
        70,
        '4 Hours',
        20,
        sectionList),

    Course(
        "11",
        "Fashion Design",
        "assets/images/c11.jpg",
        "Dive into the world of UI/UX design with our in-depth course, covering everything from user research to prototyping.",
        "Instructor:Mike W",
        "01-MAR-2022",
        4.5,
        false,
        CourseCategory.other,
        70,
        '4 Hours',
        20,
        sectionList),

    Course(
        "12",
        "MasterChef",
        "assets/images/c12.jpg",
        "Discover the art of cooking with our comprehensive course, offering hands-on experience in various cuisines and cooking methods.",
        "Instructor:Rob Moss",
        "01-MAR-2022",
        4.5,
        false,
        CourseCategory.other,
        70,
        '4 Hours',
        20,
        sectionList),


  ];
}
